name: SAST & Secrets

on:
  push:
    paths:
      - "**/*.py"
      - "security/**"
      - ".github/workflows/ci-sast-secrets.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sast-secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare folders
        run: mkdir -p EVIDENCE/P10

      # ---------- SEMGREP ----------
      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: |
            p/ci
            security/semgrep/rules.yml
          generateSarif: true
          output: EVIDENCE/P10/semgrep.sarif

      # ---------- GITLEAKS ----------
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: security/.gitleaks.toml
          report-format: json
          report-path: EVIDENCE/P10/gitleaks.json

      - name: Upload Evidence
        uses: actions/upload-artifact@v4
        with:
          name: p10-evidence
          path: EVIDENCE/P10
